export const countryName = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "The Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo",
  "Costa Rica",
  "Côte dIvoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "The Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea - Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar(Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const allCountryNationality = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "The Bahamas",
  "Bahrain",
  "Bangladeshi",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo",
  "Costa Rica",
  "Côte dIvoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "The Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea - Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "Indian",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar(Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const time_zone = [
  {
    country: "Andorra",
    code: "AD",
    zones: ["Europe/Andorra"],
  },
  {
    country: "United Arab Emirates",
    code: "AE",
    zones: ["Asia/Dubai"],
  },
  {
    country: "Afghanistan",
    code: "AF",
    zones: ["Asia/Kabul"],
  },
  {
    country: "Antigua & Barbuda",
    code: "AG",
    zones: ["America/Puerto_Rico", "America/Antigua"],
  },
  {
    country: "Anguilla",
    code: "AI",
    zones: ["America/Puerto_Rico", "America/Anguilla"],
  },
  {
    country: "Albania",
    code: "AL",
    zones: ["Europe/Tirane"],
  },
  {
    country: "Armenia",
    code: "AM",
    zones: ["Asia/Yerevan"],
  },
  {
    country: "Angola",
    code: "AO",
    zones: ["Africa/Lagos", "Africa/Luanda"],
  },
  {
    country: "Antarctica",
    code: "AQ",
    zones: [
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/Mawson",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/Troll",
      "Asia/Urumqi",
      "Pacific/Auckland",
      "Pacific/Port_Moresby",
      "Asia/Riyadh",
      "Antarctica/McMurdo",
      "Antarctica/DumontDUrville",
      "Antarctica/Syowa",
      "Antarctica/Vostok",
    ],
  },
  {
    country: "Argentina",
    code: "AR",
    zones: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Cordoba",
      "America/Argentina/Salta",
      "America/Argentina/Jujuy",
      "America/Argentina/Tucuman",
      "America/Argentina/Catamarca",
      "America/Argentina/La_Rioja",
      "America/Argentina/San_Juan",
      "America/Argentina/Mendoza",
      "America/Argentina/San_Luis",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Ushuaia",
    ],
  },
  {
    country: "Samoa (American)",
    code: "AS",
    zones: ["Pacific/Pago_Pago"],
  },
  {
    country: "Austria",
    code: "AT",
    zones: ["Europe/Vienna"],
  },
  {
    country: "Australia",
    code: "AU",
    zones: [
      "Australia/Lord_Howe",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Broken_Hill",
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Adelaide",
      "Australia/Darwin",
      "Australia/Perth",
      "Australia/Eucla",
    ],
  },
  {
    country: "Aruba",
    code: "AW",
    zones: ["America/Puerto_Rico", "America/Aruba"],
  },
  {
    country: "Åland Islands",
    code: "AX",
    zones: ["Europe/Helsinki", "Europe/Mariehamn"],
  },
  {
    country: "Azerbaijan",
    code: "AZ",
    zones: ["Asia/Baku"],
  },
  {
    country: "Bosnia & Herzegovina",
    code: "BA",
    zones: ["Europe/Belgrade", "Europe/Sarajevo"],
  },
  {
    country: "Barbados",
    code: "BB",
    zones: ["America/Barbados"],
  },
  {
    country: "Bangladesh",
    code: "BD",
    zones: ["Asia/Dhaka"],
  },
  {
    country: "Belgium",
    code: "BE",
    zones: ["Europe/Brussels"],
  },
  {
    country: "Burkina Faso",
    code: "BF",
    zones: ["Africa/Abidjan", "Africa/Ouagadougou"],
  },
  {
    country: "Bulgaria",
    code: "BG",
    zones: ["Europe/Sofia"],
  },
  {
    country: "Bahrain",
    code: "BH",
    zones: ["Asia/Qatar", "Asia/Bahrain"],
  },
  {
    country: "Burundi",
    code: "BI",
    zones: ["Africa/Maputo", "Africa/Bujumbura"],
  },
  {
    country: "Benin",
    code: "BJ",
    zones: ["Africa/Lagos", "Africa/Porto-Novo"],
  },
  {
    country: "St Barthelemy",
    code: "BL",
    zones: ["America/Puerto_Rico", "America/St_Barthelemy"],
  },
  {
    country: "Bermuda",
    code: "BM",
    zones: ["Atlantic/Bermuda"],
  },
  {
    country: "Brunei",
    code: "BN",
    zones: ["Asia/Kuching", "Asia/Brunei"],
  },
  {
    country: "Bolivia",
    code: "BO",
    zones: ["America/La_Paz"],
  },
  {
    country: "Caribbean NL",
    code: "BQ",
    zones: ["America/Puerto_Rico", "America/Kralendijk"],
  },
  {
    country: "Brazil",
    code: "BR",
    zones: [
      "America/Noronha",
      "America/Belem",
      "America/Fortaleza",
      "America/Recife",
      "America/Araguaina",
      "America/Maceio",
      "America/Bahia",
      "America/Sao_Paulo",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Santarem",
      "America/Porto_Velho",
      "America/Boa_Vista",
      "America/Manaus",
      "America/Eirunepe",
      "America/Rio_Branco",
    ],
  },
  {
    country: "Bahamas",
    code: "BS",
    zones: ["America/Toronto", "America/Nassau"],
  },
  {
    country: "Bhutan",
    code: "BT",
    zones: ["Asia/Thimphu"],
  },
  {
    country: "Botswana",
    code: "BW",
    zones: ["Africa/Maputo", "Africa/Gaborone"],
  },
  {
    country: "Belarus",
    code: "BY",
    zones: ["Europe/Minsk"],
  },
  {
    country: "Belize",
    code: "BZ",
    zones: ["America/Belize"],
  },
  {
    country: "Canada",
    code: "CA",
    zones: [
      "America/St_Johns",
      "America/Halifax",
      "America/Glace_Bay",
      "America/Moncton",
      "America/Goose_Bay",
      "America/Toronto",
      "America/Iqaluit",
      "America/Pangnirtung",
      "America/Winnipeg",
      "America/Resolute",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Swift_Current",
      "America/Edmonton",
      "America/Cambridge_Bay",
      "America/Yellowknife",
      "America/Inuvik",
      "America/Dawson_Creek",
      "America/Fort_Nelson",
      "America/Whitehorse",
      "America/Dawson",
      "America/Vancouver",
      "America/Panama",
      "America/Puerto_Rico",
      "America/Phoenix",
      "America/Blanc-Sablon",
      "America/Atikokan",
      "America/Creston",
    ],
  },
  {
    country: "Cocos (Keeling) Islands",
    code: "CC",
    zones: ["Asia/Yangon", "Indian/Cocos"],
  },
  {
    country: "Congo (Dem. Rep.)",
    code: "CD",
    zones: [
      "Africa/Maputo",
      "Africa/Lagos",
      "Africa/Kinshasa",
      "Africa/Lubumbashi",
    ],
  },
  {
    country: "Central African Rep.",
    code: "CF",
    zones: ["Africa/Lagos", "Africa/Bangui"],
  },
  {
    country: "Congo (Rep.)",
    code: "CG",
    zones: ["Africa/Lagos", "Africa/Brazzaville"],
  },
  {
    country: "Switzerland",
    code: "CH",
    zones: ["Europe/Zurich"],
  },
  {
    country: "Côte d'Ivoire",
    code: "CI",
    zones: ["Africa/Abidjan"],
  },
  {
    country: "Cook Islands",
    code: "CK",
    zones: ["Pacific/Rarotonga"],
  },
  {
    country: "Chile",
    code: "CL",
    zones: ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"],
  },
  {
    country: "Cameroon",
    code: "CM",
    zones: ["Africa/Lagos", "Africa/Douala"],
  },
  {
    country: "China",
    code: "CN",
    zones: ["Asia/Shanghai", "Asia/Urumqi"],
  },
  {
    country: "Colombia",
    code: "CO",
    zones: ["America/Bogota"],
  },
  {
    country: "Costa Rica",
    code: "CR",
    zones: ["America/Costa_Rica"],
  },
  {
    country: "Cuba",
    code: "CU",
    zones: ["America/Havana"],
  },
  {
    country: "Cape Verde",
    code: "CV",
    zones: ["Atlantic/Cape_Verde"],
  },
  {
    country: "Curaçao",
    code: "CW",
    zones: ["America/Puerto_Rico", "America/Curacao"],
  },
  {
    country: "Christmas Island",
    code: "CX",
    zones: ["Asia/Bangkok", "Indian/Christmas"],
  },
  {
    country: "Cyprus",
    code: "CY",
    zones: ["Asia/Nicosia", "Asia/Famagusta"],
  },
  {
    country: "Czech Republic",
    code: "CZ",
    zones: ["Europe/Prague"],
  },
  {
    country: "Germany",
    code: "DE",
    zones: ["Europe/Zurich", "Europe/Berlin", "Europe/Busingen"],
  },
  {
    country: "Djibouti",
    code: "DJ",
    zones: ["Africa/Nairobi", "Africa/Djibouti"],
  },
  {
    country: "Denmark",
    code: "DK",
    zones: ["Europe/Berlin", "Europe/Copenhagen"],
  },
  {
    country: "Dominica",
    code: "DM",
    zones: ["America/Puerto_Rico", "America/Dominica"],
  },
  {
    country: "Dominican Republic",
    code: "DO",
    zones: ["America/Santo_Domingo"],
  },
  {
    country: "Algeria",
    code: "DZ",
    zones: ["Africa/Algiers"],
  },
  {
    country: "Ecuador",
    code: "EC",
    zones: ["America/Guayaquil", "Pacific/Galapagos"],
  },
  {
    country: "Estonia",
    code: "EE",
    zones: ["Europe/Tallinn"],
  },
  {
    country: "Egypt",
    code: "EG",
    zones: ["Africa/Cairo"],
  },
  {
    country: "Western Sahara",
    code: "EH",
    zones: ["Africa/El_Aaiun"],
  },
  {
    country: "Eritrea",
    code: "ER",
    zones: ["Africa/Nairobi", "Africa/Asmara"],
  },
  {
    country: "Spain",
    code: "ES",
    zones: ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"],
  },
  {
    country: "Ethiopia",
    code: "ET",
    zones: ["Africa/Nairobi", "Africa/Addis_Ababa"],
  },
  {
    country: "Finland",
    code: "FI",
    zones: ["Europe/Helsinki"],
  },
  {
    country: "Fiji",
    code: "FJ",
    zones: ["Pacific/Fiji"],
  },
  {
    country: "Falkland Islands",
    code: "FK",
    zones: ["Atlantic/Stanley"],
  },
  {
    country: "Micronesia",
    code: "FM",
    zones: [
      "Pacific/Kosrae",
      "Pacific/Port_Moresby",
      "Pacific/Guadalcanal",
      "Pacific/Chuuk",
      "Pacific/Pohnpei",
    ],
  },
  {
    country: "Faroe Islands",
    code: "FO",
    zones: ["Atlantic/Faroe"],
  },
  {
    country: "France",
    code: "FR",
    zones: ["Europe/Paris"],
  },
  {
    country: "Gabon",
    code: "GA",
    zones: ["Africa/Lagos", "Africa/Libreville"],
  },
  {
    country: "Britain (UK)",
    code: "GB",
    zones: ["Europe/London"],
  },
  {
    country: "Grenada",
    code: "GD",
    zones: ["America/Puerto_Rico", "America/Grenada"],
  },
  {
    country: "Georgia",
    code: "GE",
    zones: ["Asia/Tbilisi"],
  },
  {
    country: "French Guiana",
    code: "GF",
    zones: ["America/Cayenne"],
  },
  {
    country: "Guernsey",
    code: "GG",
    zones: ["Europe/London", "Europe/Guernsey"],
  },
  {
    country: "Ghana",
    code: "GH",
    zones: ["Africa/Abidjan", "Africa/Accra"],
  },
  {
    country: "Gibraltar",
    code: "GI",
    zones: ["Europe/Gibraltar"],
  },
  {
    country: "Greenland",
    code: "GL",
    zones: [
      "America/Nuuk",
      "America/Danmarkshavn",
      "America/Scoresbysund",
      "America/Thule",
    ],
  },
  {
    country: "Gambia",
    code: "GM",
    zones: ["Africa/Abidjan", "Africa/Banjul"],
  },
  {
    country: "Guinea",
    code: "GN",
    zones: ["Africa/Abidjan", "Africa/Conakry"],
  },
  {
    country: "Guadeloupe",
    code: "GP",
    zones: ["America/Puerto_Rico", "America/Guadeloupe"],
  },
  {
    country: "Equatorial Guinea",
    code: "GQ",
    zones: ["Africa/Lagos", "Africa/Malabo"],
  },
  {
    country: "Greece",
    code: "GR",
    zones: ["Europe/Athens"],
  },
  {
    country: "South Georgia & the South Sandwich Islands",
    code: "GS",
    zones: ["Atlantic/South_Georgia"],
  },
  {
    country: "Guatemala",
    code: "GT",
    zones: ["America/Guatemala"],
  },
  {
    country: "Guam",
    code: "GU",
    zones: ["Pacific/Guam"],
  },
  {
    country: "Guinea-Bissau",
    code: "GW",
    zones: ["Africa/Bissau"],
  },
  {
    country: "Guyana",
    code: "GY",
    zones: ["America/Guyana"],
  },
  {
    country: "Hong Kong",
    code: "HK",
    zones: ["Asia/Hong_Kong"],
  },
  {
    country: "Honduras",
    code: "HN",
    zones: ["America/Tegucigalpa"],
  },
  {
    country: "Croatia",
    code: "HR",
    zones: ["Europe/Belgrade", "Europe/Zagreb"],
  },
  {
    country: "Haiti",
    code: "HT",
    zones: ["America/Port-au-Prince"],
  },
  {
    country: "Hungary",
    code: "HU",
    zones: ["Europe/Budapest"],
  },
  {
    country: "Indonesia",
    code: "ID",
    zones: ["Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"],
  },
  {
    country: "Ireland",
    code: "IE",
    zones: ["Europe/Dublin"],
  },
  {
    country: "Israel",
    code: "IL",
    zones: ["Asia/Jerusalem"],
  },
  {
    country: "Isle of Man",
    code: "IM",
    zones: ["Europe/London", "Europe/Isle_of_Man"],
  },
  {
    country: "India",
    code: "IN",
    zones: ["Asia/Kolkata"],
  },
  {
    country: "British Indian Ocean Territory",
    code: "IO",
    zones: ["Indian/Chagos"],
  },
  {
    country: "Iraq",
    code: "IQ",
    zones: ["Asia/Baghdad"],
  },
  {
    country: "Iran",
    code: "IR",
    zones: ["Asia/Tehran"],
  },
  {
    country: "Iceland",
    code: "IS",
    zones: ["Africa/Abidjan", "Atlantic/Reykjavik"],
  },
  {
    country: "Italy",
    code: "IT",
    zones: ["Europe/Rome"],
  },
  {
    country: "Jersey",
    code: "JE",
    zones: ["Europe/London", "Europe/Jersey"],
  },
  {
    country: "Jamaica",
    code: "JM",
    zones: ["America/Jamaica"],
  },
  {
    country: "Jordan",
    code: "JO",
    zones: ["Asia/Amman"],
  },
  {
    country: "Japan",
    code: "JP",
    zones: ["Asia/Tokyo"],
  },
  {
    country: "Kenya",
    code: "KE",
    zones: ["Africa/Nairobi"],
  },
  {
    country: "Kyrgyzstan",
    code: "KG",
    zones: ["Asia/Bishkek"],
  },
  {
    country: "Cambodia",
    code: "KH",
    zones: ["Asia/Bangkok", "Asia/Phnom_Penh"],
  },
  {
    country: "Kiribati",
    code: "KI",
    zones: ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"],
  },
  {
    country: "Comoros",
    code: "KM",
    zones: ["Africa/Nairobi", "Indian/Comoro"],
  },
  {
    country: "St Kitts & Nevis",
    code: "KN",
    zones: ["America/Puerto_Rico", "America/St_Kitts"],
  },
  {
    country: "Korea (North)",
    code: "KP",
    zones: ["Asia/Pyongyang"],
  },
  {
    country: "Korea (South)",
    code: "KR",
    zones: ["Asia/Seoul"],
  },
  {
    country: "Kuwait",
    code: "KW",
    zones: ["Asia/Riyadh", "Asia/Kuwait"],
  },
  {
    country: "Cayman Islands",
    code: "KY",
    zones: ["America/Panama", "America/Cayman"],
  },
  {
    country: "Kazakhstan",
    code: "KZ",
    zones: [
      "Asia/Almaty",
      "Asia/Qyzylorda",
      "Asia/Qostanay",
      "Asia/Aqtobe",
      "Asia/Aqtau",
      "Asia/Atyrau",
      "Asia/Oral",
    ],
  },
  {
    country: "Laos",
    code: "LA",
    zones: ["Asia/Bangkok", "Asia/Vientiane"],
  },
  {
    country: "Lebanon",
    code: "LB",
    zones: ["Asia/Beirut"],
  },
  {
    country: "St Lucia",
    code: "LC",
    zones: ["America/Puerto_Rico", "America/St_Lucia"],
  },
  {
    country: "Liechtenstein",
    code: "LI",
    zones: ["Europe/Zurich", "Europe/Vaduz"],
  },
  {
    country: "Sri Lanka",
    code: "LK",
    zones: ["Asia/Colombo"],
  },
  {
    country: "Liberia",
    code: "LR",
    zones: ["Africa/Monrovia"],
  },
  {
    country: "Lesotho",
    code: "LS",
    zones: ["Africa/Johannesburg", "Africa/Maseru"],
  },
  {
    country: "Lithuania",
    code: "LT",
    zones: ["Europe/Vilnius"],
  },
  {
    country: "Luxembourg",
    code: "LU",
    zones: ["Europe/Brussels", "Europe/Luxembourg"],
  },
  {
    country: "Latvia",
    code: "LV",
    zones: ["Europe/Riga"],
  },
  {
    country: "Libya",
    code: "LY",
    zones: ["Africa/Tripoli"],
  },
  {
    country: "Morocco",
    code: "MA",
    zones: ["Africa/Casablanca"],
  },
  {
    country: "Monaco",
    code: "MC",
    zones: ["Europe/Paris", "Europe/Monaco"],
  },
  {
    country: "Moldova",
    code: "MD",
    zones: ["Europe/Chisinau"],
  },
  {
    country: "Montenegro",
    code: "ME",
    zones: ["Europe/Belgrade", "Europe/Podgorica"],
  },
  {
    country: "St Martin (French)",
    code: "MF",
    zones: ["America/Puerto_Rico", "America/Marigot"],
  },
  {
    country: "Madagascar",
    code: "MG",
    zones: ["Africa/Nairobi", "Indian/Antananarivo"],
  },
  {
    country: "Marshall Islands",
    code: "MH",
    zones: ["Pacific/Tarawa", "Pacific/Kwajalein", "Pacific/Majuro"],
  },
  {
    country: "North Macedonia",
    code: "MK",
    zones: ["Europe/Belgrade", "Europe/Skopje"],
  },
  {
    country: "Mali",
    code: "ML",
    zones: ["Africa/Abidjan", "Africa/Bamako"],
  },
  {
    country: "Myanmar (Burma)",
    code: "MM",
    zones: ["Asia/Yangon"],
  },
  {
    country: "Mongolia",
    code: "MN",
    zones: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  },
  {
    country: "Macau",
    code: "MO",
    zones: ["Asia/Macau"],
  },
  {
    country: "Northern Mariana Islands",
    code: "MP",
    zones: ["Pacific/Guam", "Pacific/Saipan"],
  },
  {
    country: "Martinique",
    code: "MQ",
    zones: ["America/Martinique"],
  },
  {
    country: "Mauritania",
    code: "MR",
    zones: ["Africa/Abidjan", "Africa/Nouakchott"],
  },
  {
    country: "Montserrat",
    code: "MS",
    zones: ["America/Puerto_Rico", "America/Montserrat"],
  },
  {
    country: "Malta",
    code: "MT",
    zones: ["Europe/Malta"],
  },
  {
    country: "Mauritius",
    code: "MU",
    zones: ["Indian/Mauritius"],
  },
  {
    country: "Maldives",
    code: "MV",
    zones: ["Indian/Maldives"],
  },
  {
    country: "Malawi",
    code: "MW",
    zones: ["Africa/Maputo", "Africa/Blantyre"],
  },
  {
    country: "Mexico",
    code: "MX",
    zones: [
      "America/Mexico_City",
      "America/Cancun",
      "America/Merida",
      "America/Monterrey",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Chihuahua",
      "America/Ojinaga",
      "America/Hermosillo",
      "America/Tijuana",
      "America/Bahia_Banderas",
    ],
  },
  {
    country: "Malaysia",
    code: "MY",
    zones: ["Asia/Kuching", "Asia/Singapore", "Asia/Kuala_Lumpur"],
  },
  {
    country: "Mozambique",
    code: "MZ",
    zones: ["Africa/Maputo"],
  },
  {
    country: "Namibia",
    code: "NA",
    zones: ["Africa/Windhoek"],
  },
  {
    country: "New Caledonia",
    code: "NC",
    zones: ["Pacific/Noumea"],
  },
  {
    country: "Niger",
    code: "NE",
    zones: ["Africa/Lagos", "Africa/Niamey"],
  },
  {
    country: "Norfolk Island",
    code: "NF",
    zones: ["Pacific/Norfolk"],
  },
  {
    country: "Nigeria",
    code: "NG",
    zones: ["Africa/Lagos"],
  },
  {
    country: "Nicaragua",
    code: "NI",
    zones: ["America/Managua"],
  },
  {
    country: "Netherlands",
    code: "NL",
    zones: ["Europe/Brussels", "Europe/Amsterdam"],
  },
  {
    country: "Norway",
    code: "NO",
    zones: ["Europe/Berlin", "Europe/Oslo"],
  },
  {
    country: "Nepal",
    code: "NP",
    zones: ["Asia/Kathmandu"],
  },
  {
    country: "Nauru",
    code: "NR",
    zones: ["Pacific/Nauru"],
  },
  {
    country: "Niue",
    code: "NU",
    zones: ["Pacific/Niue"],
  },
  {
    country: "New Zealand",
    code: "NZ",
    zones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  {
    country: "Oman",
    code: "OM",
    zones: ["Asia/Dubai", "Asia/Muscat"],
  },
  {
    country: "Panama",
    code: "PA",
    zones: ["America/Panama"],
  },
  {
    country: "Peru",
    code: "PE",
    zones: ["America/Lima"],
  },
  {
    country: "French Polynesia",
    code: "PF",
    zones: ["Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"],
  },
  {
    country: "Papua New Guinea",
    code: "PG",
    zones: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  },
  {
    country: "Philippines",
    code: "PH",
    zones: ["Asia/Manila"],
  },
  {
    country: "Pakistan",
    code: "PK",
    zones: ["Asia/Karachi"],
  },
  {
    country: "Poland",
    code: "PL",
    zones: ["Europe/Warsaw"],
  },
  {
    country: "St Pierre & Miquelon",
    code: "PM",
    zones: ["America/Miquelon"],
  },
  {
    country: "Pitcairn",
    code: "PN",
    zones: ["Pacific/Pitcairn"],
  },
  {
    country: "Puerto Rico",
    code: "PR",
    zones: ["America/Puerto_Rico"],
  },
  {
    country: "Palestine",
    code: "PS",
    zones: ["Asia/Gaza", "Asia/Hebron"],
  },
  {
    country: "Portugal",
    code: "PT",
    zones: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  },
  {
    country: "Palau",
    code: "PW",
    zones: ["Pacific/Palau"],
  },
  {
    country: "Paraguay",
    code: "PY",
    zones: ["America/Asuncion"],
  },
  {
    country: "Qatar",
    code: "QA",
    zones: ["Asia/Qatar"],
  },
  {
    country: "Réunion",
    code: "RE",
    zones: ["Asia/Dubai", "Indian/Reunion"],
  },
  {
    country: "Romania",
    code: "RO",
    zones: ["Europe/Bucharest"],
  },
  {
    country: "Serbia",
    code: "RS",
    zones: ["Europe/Belgrade"],
  },
  {
    country: "Russia",
    code: "RU",
    zones: [
      "Europe/Kaliningrad",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Kirov",
      "Europe/Volgograd",
      "Europe/Astrakhan",
      "Europe/Saratov",
      "Europe/Ulyanovsk",
      "Europe/Samara",
      "Asia/Yekaterinburg",
      "Asia/Omsk",
      "Asia/Novosibirsk",
      "Asia/Barnaul",
      "Asia/Tomsk",
      "Asia/Novokuznetsk",
      "Asia/Krasnoyarsk",
      "Asia/Irkutsk",
      "Asia/Chita",
      "Asia/Yakutsk",
      "Asia/Khandyga",
      "Asia/Vladivostok",
      "Asia/Ust-Nera",
      "Asia/Magadan",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Kamchatka",
      "Asia/Anadyr",
    ],
  },
  {
    country: "Rwanda",
    code: "RW",
    zones: ["Africa/Maputo", "Africa/Kigali"],
  },
  {
    country: "Saudi Arabia",
    code: "SA",
    zones: ["Asia/Riyadh"],
  },
  {
    country: "Solomon Islands",
    code: "SB",
    zones: ["Pacific/Guadalcanal"],
  },
  {
    country: "Seychelles",
    code: "SC",
    zones: ["Asia/Dubai", "Indian/Mahe"],
  },
  {
    country: "Sudan",
    code: "SD",
    zones: ["Africa/Khartoum"],
  },
  {
    country: "Sweden",
    code: "SE",
    zones: ["Europe/Berlin", "Europe/Stockholm"],
  },
  {
    country: "Singapore",
    code: "SG",
    zones: ["Asia/Singapore"],
  },
  {
    country: "St Helena",
    code: "SH",
    zones: ["Africa/Abidjan", "Atlantic/St_Helena"],
  },
  {
    country: "Slovenia",
    code: "SI",
    zones: ["Europe/Belgrade", "Europe/Ljubljana"],
  },
  {
    country: "Svalbard & Jan Mayen",
    code: "SJ",
    zones: ["Europe/Berlin", "Arctic/Longyearbyen"],
  },
  {
    country: "Slovakia",
    code: "SK",
    zones: ["Europe/Prague", "Europe/Bratislava"],
  },
  {
    country: "Sierra Leone",
    code: "SL",
    zones: ["Africa/Abidjan", "Africa/Freetown"],
  },
  {
    country: "San Marino",
    code: "SM",
    zones: ["Europe/Rome", "Europe/San_Marino"],
  },
  {
    country: "Senegal",
    code: "SN",
    zones: ["Africa/Abidjan", "Africa/Dakar"],
  },
  {
    country: "Somalia",
    code: "SO",
    zones: ["Africa/Nairobi", "Africa/Mogadishu"],
  },
  {
    country: "Suriname",
    code: "SR",
    zones: ["America/Paramaribo"],
  },
  {
    country: "South Sudan",
    code: "SS",
    zones: ["Africa/Juba"],
  },
  {
    country: "Sao Tome & Principe",
    code: "ST",
    zones: ["Africa/Sao_Tome"],
  },
  {
    country: "El Salvador",
    code: "SV",
    zones: ["America/El_Salvador"],
  },
  {
    country: "St Maarten (Dutch)",
    code: "SX",
    zones: ["America/Puerto_Rico", "America/Lower_Princes"],
  },
  {
    country: "Syria",
    code: "SY",
    zones: ["Asia/Damascus"],
  },
  {
    country: "Eswatini (Swaziland)",
    code: "SZ",
    zones: ["Africa/Johannesburg", "Africa/Mbabane"],
  },
  {
    country: "Turks & Caicos Is",
    code: "TC",
    zones: ["America/Grand_Turk"],
  },
  {
    country: "Chad",
    code: "TD",
    zones: ["Africa/Ndjamena"],
  },
  {
    country: "French Southern & Antarctic Lands",
    code: "TF",
    zones: ["Asia/Dubai", "Indian/Maldives", "Indian/Kerguelen"],
  },
  {
    country: "Togo",
    code: "TG",
    zones: ["Africa/Abidjan", "Africa/Lome"],
  },
  {
    country: "Thailand",
    code: "TH",
    zones: ["Asia/Bangkok"],
  },
  {
    country: "Tajikistan",
    code: "TJ",
    zones: ["Asia/Dushanbe"],
  },
  {
    country: "Tokelau",
    code: "TK",
    zones: ["Pacific/Fakaofo"],
  },
  {
    country: "East Timor",
    code: "TL",
    zones: ["Asia/Dili"],
  },
  {
    country: "Turkmenistan",
    code: "TM",
    zones: ["Asia/Ashgabat"],
  },
  {
    country: "Tunisia",
    code: "TN",
    zones: ["Africa/Tunis"],
  },
  {
    country: "Tonga",
    code: "TO",
    zones: ["Pacific/Tongatapu"],
  },
  {
    country: "Turkey",
    code: "TR",
    zones: ["Europe/Istanbul"],
  },
  {
    country: "Trinidad & Tobago",
    code: "TT",
    zones: ["America/Puerto_Rico", "America/Port_of_Spain"],
  },
  {
    country: "Tuvalu",
    code: "TV",
    zones: ["Pacific/Tarawa", "Pacific/Funafuti"],
  },
  {
    country: "Taiwan",
    code: "TW",
    zones: ["Asia/Taipei"],
  },
  {
    country: "Tanzania",
    code: "TZ",
    zones: ["Africa/Nairobi", "Africa/Dar_es_Salaam"],
  },
  {
    country: "Ukraine",
    code: "UA",
    zones: ["Europe/Simferopol", "Europe/Kyiv"],
  },
  {
    country: "Uganda",
    code: "UG",
    zones: ["Africa/Nairobi", "Africa/Kampala"],
  },
  {
    country: "US minor outlying islands",
    code: "UM",
    zones: [
      "Pacific/Pago_Pago",
      "Pacific/Tarawa",
      "Pacific/Honolulu",
      "Pacific/Midway",
      "Pacific/Wake",
    ],
  },
  {
    country: "United States",
    code: "US",
    zones: [
      "America/New_York",
      "America/Detroit",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Indiana/Indianapolis",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Chicago",
      "America/Indiana/Tell_City",
      "America/Indiana/Knox",
      "America/Menominee",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/North_Dakota/Beulah",
      "America/Denver",
      "America/Boise",
      "America/Phoenix",
      "America/Los_Angeles",
      "America/Anchorage",
      "America/Juneau",
      "America/Sitka",
      "America/Metlakatla",
      "America/Yakutat",
      "America/Nome",
      "America/Adak",
      "Pacific/Honolulu",
    ],
  },
  {
    country: "Uruguay",
    code: "UY",
    zones: ["America/Montevideo"],
  },
  {
    country: "Uzbekistan",
    code: "UZ",
    zones: ["Asia/Samarkand", "Asia/Tashkent"],
  },
  {
    country: "Vatican City",
    code: "VA",
    zones: ["Europe/Rome", "Europe/Vatican"],
  },
  {
    country: "St Vincent",
    code: "VC",
    zones: ["America/Puerto_Rico", "America/St_Vincent"],
  },
  {
    country: "Venezuela",
    code: "VE",
    zones: ["America/Caracas"],
  },
  {
    country: "Virgin Islands (UK)",
    code: "VG",
    zones: ["America/Puerto_Rico", "America/Tortola"],
  },
  {
    country: "Virgin Islands (US)",
    code: "VI",
    zones: ["America/Puerto_Rico", "America/St_Thomas"],
  },
  {
    country: "Vietnam",
    code: "VN",
    zones: ["Asia/Bangkok", "Asia/Ho_Chi_Minh"],
  },
  {
    country: "Vanuatu",
    code: "VU",
    zones: ["Pacific/Efate"],
  },
  {
    country: "Wallis & Futuna",
    code: "WF",
    zones: ["Pacific/Tarawa", "Pacific/Wallis"],
  },
  {
    country: "Samoa (western)",
    code: "WS",
    zones: ["Pacific/Apia"],
  },
  {
    country: "Yemen",
    code: "YE",
    zones: ["Asia/Riyadh", "Asia/Aden"],
  },
  {
    country: "Mayotte",
    code: "YT",
    zones: ["Africa/Nairobi", "Indian/Mayotte"],
  },
  {
    country: "South Africa",
    code: "ZA",
    zones: ["Africa/Johannesburg"],
  },
  {
    country: "Zambia",
    code: "ZM",
    zones: ["Africa/Maputo", "Africa/Lusaka"],
  },
  {
    country: "Zimbabwe",
    code: "ZW",
    zones: ["Africa/Maputo", "Africa/Harare"],
  },
];
// module.exports.time_zone = time_zone;
